/**
 * Created by xudong on 17-11-14.
 */
export const GET_USER_MESSAGE='GET_USER_MESSAGE';
export const GET_USER_MESSAGE_SUCCESS='GET_USER_MESSAGE_SUCCESS';
export const GET_USER_MESSAGE_ERROR='GET_USER_MESSAGE_ERROR';
export const GET_STUDIO_ITEM='GET_STUDIO_ITEM';
export const GET_STUDIO_ITEM_SUCCESS='GET_STUDIO_ITEM_SUCCESS';
export const GET_STUDIO_ITEM_ERROR='GET_STUDIO_ITEM_ERROR';
export const GET_STUDIO_MESSAGE='GET_STUDIO_MESSAGE';
export const GET_STUDIO_MESSAGE_SUCCESS='GET_STUDIO_MESSAGE_SUCCESS';
export const GET_STUDIO_MESSAGE_ERROR='GET_STUDIO_MESSAGE_ERROR';
export const GET_SEATS='GET_SEATS';
export const GET_SEATS_SUCCESS='GET_SEATS_SUCCESS';
export const GET_SEATS_ERROR='GET_SEATS_ERROR';